### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by wyy010417** [Elm-Forest/AutoOffice#1]
大佬这个没有前端代码吗

**Comment by Elm-Forest** [comment]
有的：https://github.com/Elm-Forest/OA-vue
前端还有一部分没开发完，不过能正常使用
还有就是本项目已经过时，刚刚提交最新的版本，注意更新

**Comment by wyy010417** [comment]
万分感谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Elm-Forest/AutoOffice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 晚上11:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Elm-Forest/AutoOffice] 求助 (Issue #1)





 
有的：https://github.com/Elm-Forest/OA-vue
 前端还有一部分没开发完，不过能正常使用
 还有就是本项目已经过时，刚刚提交最新的版本，注意更新
